/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ControldeExistencias;

import MenuPrincipal.Principal;

/**
 *
 * @author Bienc
 */
public class ControlExistenciasMenu extends javax.swing.JFrame {

    /**
     * Creates new form ControlExistenciasMenu
     */
    public ControlExistenciasMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        EntradaProducto = new javax.swing.JButton();
        SalidaProductos = new javax.swing.JButton();
        AlertaStock = new javax.swing.JButton();
        MovimientoStock = new javax.swing.JButton();
        Regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Control de Existencias");

        EntradaProducto.setText("Resgistro de entrada de Productos");
        EntradaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaProductoActionPerformed(evt);
            }
        });

        SalidaProductos.setText("Registro de Salida de Productos");
        SalidaProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalidaProductosActionPerformed(evt);
            }
        });

        AlertaStock.setText("Alertas de Stock Bajo");
        AlertaStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlertaStockActionPerformed(evt);
            }
        });

        MovimientoStock.setText("Historal de Movimientos de Stock");
        MovimientoStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovimientoStockActionPerformed(evt);
            }
        });

        Regresar.setText("Regresar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(137, 137, 137))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EntradaProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SalidaProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AlertaStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MovimientoStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(Regresar)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(EntradaProducto)
                .addGap(18, 18, 18)
                .addComponent(SalidaProductos)
                .addGap(18, 18, 18)
                .addComponent(AlertaStock)
                .addGap(18, 18, 18)
                .addComponent(MovimientoStock)
                .addGap(18, 18, 18)
                .addComponent(Regresar)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EntradaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaProductoActionPerformed
   
   EntradaProductos newframe = new EntradaProductos();    
   newframe.setVisible(true);
     
this.dispose();   
        
    }//GEN-LAST:event_EntradaProductoActionPerformed

    private void SalidaProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalidaProductosActionPerformed
    SalidaProductos newframe = new SalidaProductos();    
   newframe.setVisible(true);
     
this.dispose();
    }//GEN-LAST:event_SalidaProductosActionPerformed

    private void AlertaStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlertaStockActionPerformed
    AlertaStockBajo newframe = new AlertaStockBajo();    
   newframe.setVisible(true);
     
this.dispose();
    }//GEN-LAST:event_AlertaStockActionPerformed

    private void MovimientoStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovimientoStockActionPerformed
     MovimientosStock newframe = new MovimientosStock();    
   newframe.setVisible(true);
     
this.dispose();
    }//GEN-LAST:event_MovimientoStockActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
     Principal  newframe = new Principal();    
   newframe.setVisible(true);
     
this.dispose();
    }//GEN-LAST:event_RegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlExistenciasMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlExistenciasMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlExistenciasMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlExistenciasMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlExistenciasMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlertaStock;
    private javax.swing.JButton EntradaProducto;
    private javax.swing.JButton MovimientoStock;
    private javax.swing.JButton Regresar;
    private javax.swing.JButton SalidaProductos;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
