/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GestionProductos;

/**
 *
 * @author Bienc
 */
public class nuevaCaracteristica extends javax.swing.JFrame {

    /**
     * Creates new form nuevaCaracteristica
     */
    public nuevaCaracteristica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Newdescripcion = new javax.swing.JTextField();
        cancelarcaracteristica = new javax.swing.JButton();
        guardarcaracteristica = new javax.swing.JButton();
        nombrecarateristica = new javax.swing.JLabel();
        Newcaracteristica = new javax.swing.JTextField();
        descripcincaracteristica = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Newdescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewdescripcionActionPerformed(evt);
            }
        });

        cancelarcaracteristica.setText("Cancelar");
        cancelarcaracteristica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarcaracteristicaActionPerformed(evt);
            }
        });

        guardarcaracteristica.setText("Guardar");
        guardarcaracteristica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarcaracteristicaActionPerformed(evt);
            }
        });

        nombrecarateristica.setText("Nombre:");

        Newcaracteristica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewcaracteristicaActionPerformed(evt);
            }
        });

        descripcincaracteristica.setText("Descripción:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(nombrecarateristica, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(descripcincaracteristica)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Newcaracteristica)
                    .addComponent(Newdescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(cancelarcaracteristica)
                .addGap(52, 52, 52)
                .addComponent(guardarcaracteristica)
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombrecarateristica, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Newcaracteristica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descripcincaracteristica)
                    .addComponent(Newdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarcaracteristica)
                    .addComponent(guardarcaracteristica))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewdescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewdescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewdescripcionActionPerformed

    private void cancelarcaracteristicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarcaracteristicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarcaracteristicaActionPerformed

    private void guardarcaracteristicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarcaracteristicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarcaracteristicaActionPerformed

    private void NewcaracteristicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewcaracteristicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewcaracteristicaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nuevaCaracteristica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nuevaCaracteristica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nuevaCaracteristica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nuevaCaracteristica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nuevaCaracteristica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Newcaracteristica;
    private javax.swing.JTextField Newdescripcion;
    private javax.swing.JButton cancelarcaracteristica;
    private javax.swing.JLabel descripcincaracteristica;
    private javax.swing.JButton guardarcaracteristica;
    private javax.swing.JLabel nombrecarateristica;
    // End of variables declaration//GEN-END:variables
}
